### ISSUE TITLE
GitHub reporter support

### ISSUE THREAD

**Issue by GiedriusS** [cloudflare/pint#15]
Hello! Thanks for this software. It would be ideal to support GitHub, not just BitBucket as a platform where detected issues could be reported. What do you think? Would you be open to accepting pull requests implementing such a feature?

**Comment by GiedriusS** [comment]
@prymitive any opinion on this? Kind ping.

**Comment by prymitive** [comment]
I’d be more than happy to add that.
It might require additional authentication options for Prometheus server so actions are able to access cloud deployments.

All the code we lint internally is on bitbucket and so that’s the only integration we have. There’s no other reason that would prevent adding GitHub support.

**Comment by GiedriusS** [comment]
Closing this as https://github.com/cloudflare/pint/pull/18 has been merged :heart:
