### ISSUE TITLE
Provide alternative to yaml comments for configuring linting rules

### ISSUE THREAD

**Issue by mario-steinhoff-gcx** [cloudflare/pint#404]
Hey, just discovered this tool, awesome work!

We would like to use pint in watch mode for continous scanning of our prometheus rules, and use the owner feature so we can route alerts for problems to the right team.

Unfortunately, pint linting rules can only be configured via yaml comments, but we use jsonnet to generate our prometheus rules (serializing them to yaml via `std.manifestYamlDoc()`) and I couldn't find a way to add comments to the generated output. I am no jsonnet expert but it looks like the design of jsonnet doesn't even allow this.

Our primary motivation for jsonnet is that we can use the existing [monitoring-mixins](https://monitoring.mixins.dev/) ecosystem and get an improved authoring experience over raw yaml - which works pretty well so far.

Some linters allow their rules to be configured in external config files, e.g. in PMD you can define [rulesets](https://pmd.github.io/latest/pmd_userdocs_making_rulesets.html) - but I wouldn't use XML today :-)  I havent thought about how this could look in detail but in general I think such a mechanism could solve our problem.

Would you be open to implement or accept a PR for such a feature?

**Comment by prymitive** [comment]
What kind of rules are you looking to add?

Comments are used mostly for rule level overrides, rules themselves have minimal configuration which is set in a config file.
This is a common pattern among tools that are checking source code. pint is not unique here.

It's comments because this allows to place any overrides next to the source code they are for. Any other solution would require you to write your rule in one place and then add a pint override in another place, which will make maintenance of those rules much more difficult.
There are some things that could be configured centrally, since they don't change much, like file ownership, but I wouldn't add any central mapping of everything that everyone can set, that's just gonna get messy.
Maybe you should report a bug/request to jsonnet?

**Comment by prymitive** [comment]
> Where I would have expected that this passes, since there is a more specific rule block that overrides settings for the same annotation check.

If it matches it applies, it doesn't matter than there's another rule that also matches.
If you want to exclude a subset of rules then add an `ignore`.

**Comment by LeoQuote** [comment]
It could be useful if it's possible to ignore an alert in `annotations`, we're using prometheus operator as well, the comment in yaml will disappear in the output prometheus rules.
