### ISSUE TITLE
More lenient alerts/template rule

### ISSUE THREAD

**Issue by bilbof** [cloudflare/pint#531]
## Problem

I've disabled the `alerts/template` rule since it was a bit too broad. Currently validation will fail against the alerts in the examples below when the `alerts/template` check is enabled, but it would be nice if we had a workaround so we could still use `alerts/template`.

### Example 1: "absent is not passing it"

```
alert: alertname
annotations: { message: "Alert is firing or metric is missing {{ $labels.cluster }}" }
expr: metric > 1 or absent(metric)
```

Error:

> template is using "cluster" label but absent() is not passing it (alerts/template)

### Example 2: "the query removes it"

In this case we are using external labels but have not connected pint to Prometheus. It would be great to specify the prometheus external labels in the pint config file.

E.g. we have set the external label `cluster` 

```
alert: alertname
annotations: { message: "Alert is firing cluster={{ $labels.cluster }}" }
expr: sum(metric) > 1
```

> template is using "cluster" label but the query removes it (alerts/template)

## Proposed solution

* Ignore 'absent is not passing it' (otherwise we'd need to create a separate `absent` alert for every alert - but maybe this is best practice) - solves example 1
* Allow setting a hardcoded list of external labels in the pint config file - solves example 2

**Comment by prymitive** [comment]
pint could and probably should read external labels from configuration, so that's need fixing.

Also, external labels can be accessed in templates via `$externalLabels`, but I don't think handles that correctly. If it did and you had `"Alert is firing cluster={{ $externalLabels.cluster }}"` it would validate everything correctly. So that's another issue to solve.

So, for starters, I should make pint read external labels from Prometheus config and populate `$externalLabels` with that information. The downside is that this makes `alerts/template` an "online" check instead of "offline" (it needs to connect to Prometheus to run).

Secondary issue here is, as you noted, that as checks get more things to validate there's a growing number of problems bundled under the same label. That's a bigger issue and I think it could be solved by adding unique identifiers to each different problem category, so you can target suppression in a more granular way.

**Comment by bilbof** [comment]
AFAICT this works.

**Comment by AmandeepSaxena** [comment]
is this fixed? @prymitive 
1. Currently we face the same issue while using ` annotations:
            identifier: method = "{{ $labels.transaction_type }}"`
            
            and pint throw an error `Bug: template is using "method" label but the query removes it (alerts/template)`
            so in place of labels we used $externalLabels. Though it resolved the issue but will it going to contain accurate info? 
            2. Can we resolve such issues by doing pint dynamic check with our internal prom server ?Can you also help me telling how currently it checks the rules?

**Comment by AmandeepSaxena** [comment]
is this fixed? @prymitive

Currently we faced the same issue while using  annotations: identifier: method = "{{ $labels.transaction_type }}"
and pint throw an error Bug: template is using "method" label but the query removes it (alerts/template)
so in place of labels we used $externalLabels. Though it resolved the issue but will it going to contain accurate info?
2. Can we resolve such issues by doing pint dynamic check with our internal prom server ?Can you also help me telling how currently it checks the rules?

**Comment by prymitive** [comment]
> AFAICT this works.

The code seems very clear to me:
https://github.com/prometheus/prometheus/blob/main/template/template.go#L357-L370

`{{ $labels }}` and `{{ $externaLabels }}` are populated from two different sources.
I don't see how you could possibly end up with a value for `{{ $labels.cluster }}` if your query doesn't supply it. Even if you do have it configured under `external_labels`.
