### ISSUE TITLE
Failing to POST PR review comments when additional commits added

### ISSUE THREAD

**Issue by wbh1** [cloudflare/pint#640]
Basically, the same issue as https://github.com/cloudflare/pint/issues/478.

**Environment**: Github Enterprise Server 3.8
**Pint version**: 0.43.1

Steps:
1. Submit PR with pint running in CI mode
2. Pint successfully submits a PR review with comments
3. Address comments and push new commit(s)
4. Pint fails with this error (put on multiple lines for readability):
```console
level=fatal msg="Execution completed with error(s)"
error="submitting reports: 
POST https://<REDACTED>/api/v3/repos/ops/prometheus_rules/pulls/244/comments: 
422 Validation Failed [{Resource:PullRequestReviewComment Field:pull_request_review_thread.start_line
Code:custom Message:pull_request_review_thread.start_line must be part of the same hunk as the line.}]"
```

Potentially also worth noting, the comment is related to the `promql/series` check. However, this PR did not modify the `expr`, only an `annotation` -- so should this even be being attempted to be sent as feedback? Or should it be skipped like other things (e.g. the multiple times we see `Problem reported on unmodified line, skipping`)?

For context, the sole comment that is trying to be added (after the feedback from the initial commit), is this:
```console
level=debug msg="Creating review comment"
body="[promql/series](https://cloudflare.github.io/pint/checks/promql/series.html):
metric \"http_requests_total\" with label {code=~\"5..\"} is only sometimes present on prometheus \"infra_dallas\" at https://<REDACTED> with average life span of 12h10m42s" commit=55b1b1cb3391892fe2dffd8114e8f126f554b13f
```

**Comment by prymitive** [comment]
https://docs.github.com/en/rest/pulls/reviews#create-a-review-for-a-pull-request does not mention any restrictions on start_line but it does sound like it doesn't allow the review comment because it's on a non-modified line.

BitBucket limits that and so there's extra code to move annotations to the nearest modified line if needed, which I never liked much.
Need to test this to verify but if the API is really limiting us here then we might need the same trick on GH reporter as we already have on BB one.
